### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by horoiwa** [horoiwa/kaleido#1]
- [ ] y-y plot and PCA

- [ ] DataProfiling (pair, predict, dataframe)

- [ ] paralell plot with DataFrame

- [ ] Triangle scatter PCA

**Comment by horoiwa** [comment]
- [ ] scatter plot, input: dataframe and show index  on hover

**Comment by horoiwa** [comment]
- [ ] PCA Distribution plot
